Imaginea/KodeBeagle

plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/BetterDocsAction.java, plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/EditorToggleAction.java
Fixed null pointer exception for code folding in the plugin editor.
=> added support for selection in editor and minor fixes

plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/ESUtils.java, plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/EditorDocOps.java, plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/MainWindow.java, plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/ProjectTree.java, plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/RefreshAction.java, plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/WindowEditorOps.java
modified wrong esURL message
disposed tiny editors in code pane after usage
fixed some checkstyle voilations
fixes #112
=> [ideaplugin] removed foldings from main pane editor

plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/RefreshAction.java
so that user can see 'no results...' info message
fixes #137 
fixes #142
=> [ideapluign]bringing back focus to main pane if es returns no results

plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/RefreshAction.java
Removed JButton and added JLabel with mouse listener
Fixes #138
=> [ideaplugin] #138 reduced size of tiny editor title

plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/RefreshAction.java, plugins/idea/betterdocsidea/src/main/resources/META-INF/plugin.xml
fixes #131 and #127
review by @amit-shar
=> Introduced async fetching of results from elastic search server.

plugins/idea/betterdocsidea/src/main/java/com/imaginea/betterdocs/RefreshAction.java
=> [idea] Repo name opens github on mouse click

core/src/main/scala/com/kodebeagle/parser/MethodVisitor.java, core/src/test/resources/TransportClient.java, core/src/test/scala/com/kodebeagle/indexer/JavaFileIndexerSuite.scala, core/src/test/scala/com/kodebeagle/parser/ParserSuite.scala
=> [core] #243 Added annotations to the index.

plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/ui/LegalNotice.java, plugins/idea/kodebeagleidea/src/main/resources/META-INF/plugin.xml, resources/TestPlan.md
=> [idea] #250 made kodebeagle name consistent across project

library/dev/js/factories/docs-service-factory.js
My editor doesn't like tabs on empty lines
=> - disabling intro tour in search page

resources/sampleQueries.md
=> [docs] #376 Queries using filters for imports and related methods

plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/ui/MainWindow.java, plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/ui/ProjectTree.java, plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/ui/SpotlightPane.java
=> [idea] #396 Fixed assertion error on windows when file opened 

library/dev/js/factories/docs-service-factory.js, library/dev/js/modules/update-editors-list.js
Fix for #366.. (changes on top of branch issue#363)
@hashd
=> Issue#363#366 fine tuning in the file content request from front end

plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/util/ESUtils.java
=> [idea] #420 Ignored files whose content is null

plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/util/EditorDocOps.java
=> [idea] #445 Fixed package name collision in project and external jar

library/dev/js/modules/code-snippet-search.js
=> [web-ui] #429 Fixes bug in website by not considering quoted string

plugins/idea/common/checkstyle-config.xml, plugins/idea/common/src/main/java/com/imaginea/kodebeagle/ui/MainWindowBase.java, plugins/idea/common/src/main/java/com/imaginea/kodebeagle/ui/ProjectTree.java, plugins/idea/javaPlugin/checkstyle-config.xml
=> [idea] #447 Fixed NPE while opening file

bin/upload_to_es.sh, core/src/main/scala/com/kodebeagle/indexer/IndexEntities.scala, core/src/main/scala/com/kodebeagle/indexer/JavaASTBasedIndexerForMethods.scala, core/src/main/scala/com/kodebeagle/indexer/JavaFileIndexer.scala, core/src/main/scala/com/kodebeagle/parser/ScalaParser.scala, core/src/test/scala/com/kodebeagle/indexer/JavaFileIndexerSuite.scala
=> [idea] #453 Added language field to importsmethods index

core/src/main/scala/com/kodebeagle/crawler/ZipBasicParser.scala, core/src/main/scala/com/kodebeagle/indexer/JavaASTBasedIndexerForMethods.scala, core/src/main/scala/com/kodebeagle/parser/JsParser.scala, core/src/main/scala/com/kodebeagle/spark/CreateJsIndexJob.scala, core/src/test/resources/Test.js, core/src/test/scala/com/kodebeagle/parser/ParserSuite.scala, project/Build.scala
=> [core] #474 Added support for indexing javascript code in NPM packages

plugins/chrome/src/content_script.js
1. Added column numbers to dom elements for capturing & match meta information.
2. Navigation based on interaction within file and external files.
3. Popup visual enhancements.
fixes #480
closes #484
=> [chrome] #480 Chrome extension changes

core/src/main/scala/com/kodebeagle/indexer/ScalaExternalTypeRefIndexer.scala, core/src/main/scala/com/kodebeagle/indexer/ScalaIndexerUtils.scala, core/src/main/scala/com/kodebeagle/parser/ScalaParser.scala
=> [core] #488 Fixes the issue of prefixed imports

.travis.yml, core/src/main/scala/com/kodebeagle/indexer/JavaExternalTypeRefIndexer.scala, core/src/main/scala/com/kodebeagle/indexer/JavaTypeRefIndexer.scala, core/src/main/scala/com/kodebeagle/spark/ConsolidatedIndexJob.scala
moving broadcast outiside the closure
fixes #498
closes #499
=> [core] #498 Fixes the bug by implementing serializable and

core/src/main/scala/com/kodebeagle/crawler/ZipBasicParser.scala
=> [core] #502 Extracts packages from source files

core/src/main/scala/com/kodebeagle/hadoop/ZipFileInputFormat.scala, core/src/main/scala/com/kodebeagle/hadoop/ZipFileRecordReader.scala, core/src/main/scala/com/kodebeagle/spark/ConsolidatedIndexJob.scala, core/src/main/scala/com/kodebeagle/spark/SparkIndexJobHelper.scala
=> [core] #503 Replaces sc.binaryFiles by sc.newAPIHadoopFile

_includes/search-result/files-content.html, library/less/search/defaults.less, search/index.html
Changes the github, expand and collaspe images on results page.
=> Changed the github, expand and collaspe images on results page.

core/src/main/java/com/kodebeagle/javaparser/MethodInvocationResolver.java, core/src/main/java/com/kodebeagle/javaparser/SingleClassBindingResolver.java, core/src/main/java/com/kodebeagle/javaparser/TypeResolver.java, core/src/main/scala/com/kodebeagle/indexer/FileMetaDataIndexer.scala, core/src/main/scala/com/kodebeagle/indexer/IndexEntities.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/test/resources/EnumTypeTest.java, core/src/test/scala/com/kodebeagle/model/GithubRepoSuite.scala, core/src/test/scala/com/kodebeagle/parser/MethodInvocationResolverSuite.scala
=> [core] #509 Enum and multiple supertypes support

core/src/main/scala/com/kodebeagle/indexer/FileMetaDataIndexer.scala, core/src/main/scala/com/kodebeagle/indexer/IndexEntities.scala, core/src/main/scala/com/kodebeagle/model/GithubRepo.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/test/scala/com/kodebeagle/model/GithubRepoSuite.scala, core/src/test/scala/com/kodebeagle/model/JavaRepoTestSuite.scala, core/src/test/scala/com/kodebeagle/model/Mocks.scala
=> [core] #551 Fixes file path for a repo file.

core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/main/scala/com/kodebeagle/spark/RepoAnalyzerJob.scala, core/src/test/scala/com/kodebeagle/model/JavaRepoTestSuite.scala
Also modifies the RepoAnalyzer job to read in multiple files based names passed as arguments.
fixes #552
closes #554
=> [core] #552 Add a new line for ever index entry.

.gitignore, core/src/main/java/com/kodebeagle/javaparser/MethodInvocationResolver.java, core/src/main/java/com/kodebeagle/javaparser/SingleClassBindingResolver.java, core/src/main/scala/com/kodebeagle/crawler/GithubApiHelper.scala, core/src/main/scala/com/kodebeagle/indexer/FileMetaDataIndexer.scala, core/src/main/scala/com/kodebeagle/indexer/IndexEntities.scala, core/src/main/scala/com/kodebeagle/indexer/ScalaIndexerUtils.scala, core/src/main/scala/com/kodebeagle/indexer/ScalaTypeRefIndexer.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/main/scala/com/kodebeagle/parser/JsParser.scala, core/src/main/scala/com/kodebeagle/spark/RepoAnalyzerJob.scala, core/src/main/scala/com/kodebeagle/util/SparkIndexJobHelper.scala, core/src/main/scala/com/kodebeagle/util/Utils.scala, core/src/test/java/com/kodebeagle/parser/ASTParserTest.java, core/src/test/scala/com/kodebeagle/model/JavaRepoTestSuite.scala, core/src/test/scala/com/kodebeagle/parser/MethodInvocationResolverSuite.scala, core/src/test/scala/com/kodebeagle/parser/ParserSuite.scala
=> [core] #567 Refactors type reference index

core/src/main/java/com/kodebeagle/javaparser/MethodInvocationResolver.java, core/src/main/java/com/kodebeagle/javaparser/SingleClassBindingResolver.java, core/src/main/resources/application.properties, core/src/main/scala/com/kodebeagle/configuration/KodeBeagleConfig.scala, core/src/main/scala/com/kodebeagle/indexer/IndexEntities.scala, core/src/main/scala/com/kodebeagle/indexer/IndexEntitiesTraits.scala, core/src/main/scala/com/kodebeagle/indexer/JavaIndexHelpers.scala, core/src/main/scala/com/kodebeagle/model/GithubRepoUpdateHelper.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/main/scala/com/kodebeagle/spark/RepoAnalyzerJob.scala, core/src/test/resources/JavadocParsingTestClass.java, core/src/test/scala/com/kodebeagle/parser/JavaParserSuite.scala
578 Documentation Index for Java repos
579 Configuration in application.properties for fsRepoDirPath in GithubRepoUpdateHelper
580 Error Handing for corrupted github metadata files
fixes #578
fixes #579
fixes #580
closes #582
=>   [core] #578 Documentation Index for Java repos

core/src/main/java/com/kodebeagle/javaparser/MethodInvocationResolver.java, core/src/main/resources/application.properties, core/src/main/scala/com/kodebeagle/configuration/KodeBeagleConfig.scala, core/src/main/scala/com/kodebeagle/indexer/IndexEntities.scala, core/src/main/scala/com/kodebeagle/indexer/JavaIndexHelpers.scala, core/src/main/scala/com/kodebeagle/indexer/TypeAggregator.scala, core/src/main/scala/com/kodebeagle/spark/RepoAnalyzerJob.scala, core/src/main/scala/com/kodebeagle/spark/TypeAggregationJob.scala, core/src/test/scala/com/kodebeagle/model/JavaRepoTestSuite.scala
1. Also adds repo stats per type.
2. Removes constructors as methods per type.
fixes #583
closes #584
=> [core] #583 Removes camel case from method suggest.

bin/upload_to_es.sh, core/src/test/scala/com/kodebeagle/model/GithubRepoSuite.scala
and [filetype] field in filemetadata
closes #590
closes #591
=> [core] #590 Fixes mapping for [name] field in aggregation

core/src/main/scala/com/kodebeagle/model/GithubRepo.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/main/scala/com/kodebeagle/spark/RepoAnalyzerJob.scala, core/src/test/scala/com/kodebeagle/model/GithubRepoSuite.scala, core/src/test/scala/com/kodebeagle/model/Mocks.scala, project/Build.scala
1. Adds new indices for repositories.
2. Collects file/repo git stats and produce indices.
fixes #596
fixes #595 
closes #597
=> New repo indices and git stats

bin/upload_to_es.sh, core/src/main/scala/com/kodebeagle/indexer/IndexEntities.scala, core/src/main/scala/com/kodebeagle/indexer/JavaIndexHelpers.scala, core/src/main/scala/com/kodebeagle/model/GithubRepo.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/main/scala/com/kodebeagle/spark/RepoAnalyzerJob.scala, core/src/test/scala/com/kodebeagle/model/JavaRepoTestSuite.scala, core/src/test/scala/com/kodebeagle/parser/JavaParserSuite.scala
=> [core] #593 Incorrect structure for documentation index

bin/upload_to_es.sh, project/plugins.sbt
=> [core] #598 Adds mapping for repo and file details types

core/src/main/scala/com/kodebeagle/model/GithubRepo.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/main/scala/com/kodebeagle/model/Repo.scala, core/src/main/scala/com/kodebeagle/model/ScalaRepo.scala, core/src/main/scala/com/kodebeagle/spark/RepoAnalyzerJob.scala, core/src/test/scala/com/kodebeagle/model/GithubRepoSuite.scala, core/src/test/scala/com/kodebeagle/model/JavaRepoTestSuite.scala
Also changed the repo git aggregation logic so that minimum things are kept around in memory.
fixes #602
closes #603
=> [core] #602 Modified repo interface to return iterator over files her than a concrete collection.

core/src/main/resources/application.properties, core/src/main/scala/com/kodebeagle/configuration/KodeBeagleConfig.scala, core/src/main/scala/com/kodebeagle/indexer/TypeAggregator.scala, core/src/main/scala/com/kodebeagle/model/GithubRepo.scala, core/src/main/scala/com/kodebeagle/model/JavaRepo.scala, core/src/main/scala/com/kodebeagle/spark/EsUploaderJob.scala, core/src/main/scala/com/kodebeagle/spark/LazyWholeTextFileInputFormat.scala, core/src/main/scala/com/kodebeagle/spark/LazyWholeTextFileRecordReader.scala, core/src/main/scala/com/kodebeagle/spark/SmartWholeTextFileRDD.scala, core/src/test/scala/com/kodebeagle/model/GithubRepoSuite.scala, project/Build.scala
- Added typeName as well to type suggestion input.
- Most changed files limit set to 10.
- Changed ESUploader job to consolidate and update files.
- Smart whole text file format.
- Made changes to commit format. Added random string to camel case suggests.
fixes #604
closes #605
=> [core] #604 Adds the ES uploader job.

_includes/search-result/methods.html, library/dev/js/controller/editors-controller.js, library/dev/js/directives/init-model-directive.js
=> [WEB-UI] Undefined shows up in search bar when user selects.

.travis.yml
downloading scala plugin
fixes #650
closes #651
=> [core] #650 Fixes wget SSL error in travis build while

README.md
Fixed Markdown snippets for hyperlinks.
=> [docs] #652 Fix hyperlinks in README.md
